# -*- coding: utf-8 -*-

YEAR_CHOICES = (
    ('', '---------'),
    ('1', 'Freshman'),
    ('2', 'Sophmore'),
    ('3', 'Junior'),
    ('4', 'Senior'),
)
GRADUATE_DEGREE = (
    ('M.S.', 'M.S.'),
    ('Ph.D', 'Ph.D'),
    ('M.D.', 'M.D.'),
    ('Other', 'Other'),
)
GRANTS_PROCESS_STAGES = (
    ('', '---------'),
    ('Pre-Award (Application Process)', 'Pre-Award (Application Process)'),
    (
        'Post-Award (Award Acceptance/Grant Management)',
        'Post-Award (Award Acceptance/Grant Management)',
    ),
    ('Both', 'Both'),
)
UNDERGRADUATE_DEGREE = (
    ("Bachelor's degree", "Bachelor's degree"),
    ("Associate's degree/certificate", "Associate's degree/certificate"),
)
WSGC_SCHOOL = (
    ('Alverno College', 'Alverno College'),
    ('Carthage College', 'Carthage College'),
    ('Chief Dull Knife College', 'Chief Dull Knife College'),
    ('College of Menominee Nation', 'College of Menominee Nation'),
    ('Colorado School of Mines', 'Colorado School of Mines'),
    ('Concordia University', 'Concordia University'),
    ('Lawrence University', 'Lawrence University'),
    ('Leech Lake Tribal College', 'Leech Lake Tribal College'),
    ('Little Big Horn College', 'Little Big Horn College'),
    ('Marquette University', 'Marquette University'),
    ('Medical College of Wisconsin', 'Medical College of Wisconsin'),
    ('Milwaukee School of Engineering', 'Milwaukee School of Engineering'),
    ('Moraine Park Technical College', 'Moraine Park Technical College'),
    ('Northern Arizona University', 'Northern Arizona University'),
    ('Northwest Indian College', 'Northwest Indian College'),
    ('Ripon College', 'Ripon College'),
    ('St. Norbert College', 'St. Norbert College'),
    ('Turtle Mountain Community College', 'Turtle Mountain Community College'),
    ('University of Alaska-Fairbanks', 'University of Alaska-Fairbanks'),
    ('University of California-Los Angeles', 'University of California-Los Angeles'),
    ('UW Fox Valley', 'UW Fox Valley'),
    ('UW Green Bay', 'UW Green Bay'),
    ('UW LaCrosse', 'UW LaCrosse'),
    ('UW Madison', 'UW Madison'),
    ('UW Milwaukee', 'UW Milwaukee'),
    ('UW Oshkosh', 'UW Oshkosh'),
    ('UW Parkside', 'UW Parkside'),
    ('UW Platteville', 'UW Platteville'),
    ('UW River Falls', 'UW River Falls'),
    ('UW Sheboygan', 'UW Sheboygan'),
    ('UW Stevens Point', 'UW Stevens Point'),
    ('UW Stout', 'UW Stout'),
    ('UW Superior', 'UW Superior'),
    ('UW Washington County', 'UW Washington County'),
    ('UW Whitewater', 'UW Whitewater'),
    ('Utah State University-Eastern Blanding', 'Utah State University-Eastern Blanding'),
    ('Western Technical College', 'Western Technical College'),
    ('Wisconsin Lutheran College', 'Wisconsin Lutheran College'),
    ('Other', 'Other'),
)
MAJORS = (
    ('Aeronautical Engineering', 'Aeronautical Engineering'),
    ('Aerospace Engineering', 'Aerospace Engineering'),
    ('Applied Physics', 'Applied Physics'),
    ('Astronomy', 'Astronomy'),
    ('Astrophysics', 'Astrophysics'),
    ('Atmoshperic Sciences', 'Atmoshperic Sciences'),
    ('Biochemistry', 'Biochemistry'),
    ('Biology', 'Biology'),
    ('Biomedical Engineering', 'Biomedical Engineering'),
    ('Biomedical Science', 'Biomedical Science'),
    ('Biophysics', 'Biophysics'),
    ('Biotechnology', 'Biotechnology'),
    ('Chemical Engineering', 'Chemical Engineering'),
    ('Chemistry', 'Chemistry'),
    ('Civil Engineering', 'Civil Engineering'),
    ('Computer Engineering', 'Computer Engineering'),
    ('Computer Science', 'Computer Science'),
    ('Electrical Engineering', 'Electrical Engineering'),
    ('Environmental Science', 'Environmental Science'),
    ('Environmental Studies', 'Environmental Studies'),
    ('Geography', 'Geography'),
    ('Geology', 'Geology'),
    ('Geophysics', 'Geophysics'),
    ('Geoscience', 'Geoscience'),
    ('Industrial Engineering', 'Industrial Engineering'),
    ('Kinesiology', 'Kinesiology'),
    ('Mathematics', 'Mathematics'),
    ('Mechanical Engineering', 'Mechanical Engineering'),
    ('Meteorology', 'Meteorology'),
    ('Microbiology', 'Microbiology'),
    ('Molecular and Cell Biology', 'Molecular and Cell Biology'),
    (
        'Molecular and Environmental Plant Science',
        'Molecular and Environmental Plant Science',
    ),
    ('Neuroscience', 'Neuroscience'),
    ('Nuclear Engineering', 'Nuclear Engineering'),
    ('Oceanography', 'Oceanography'),
    ('Other', 'Other'),
    ('Physics', 'Physics'),
    ('Statistics', 'Statistics'),
    ('Systems Engineering', 'Systems Engineering'),
)
PROGRAM_CHOICES = (
    ('AerospaceOutreach', 'Aerospace Outreach'),
    ('ClarkGraduateFellowship', 'Dr. Laurel Salton Clark Memorial Research Fellowship'),
    ('CollegiateRocketCompetition', 'Collegiate Rocket Competition'),
    ('EarlyStageInvestigator', 'Early-Stage Investigator'),
    ('FirstNationsRocketCompetition', 'First Nations Rocket Competition'),
    ('GraduateFellowship', 'WSGC Graduate and Professional Research Fellowship'),
    ('HighAltitudeBalloonLaunch', 'High Altitude Balloon Launch'),
    ('HigherEducationInitiatives', 'Higher Education Initiatives'),
    ('IndustryInternship', 'Industry Internship'),
    ('MidwestHighPoweredRocketCompetition', 'Midwest High Powered Rocket Competition'),
    ('NasaCompetition', 'NASA Competition'),
    ('ProfessionalProgramStudent', 'Professional Program Student'),
    ('ResearchInfrastructure', 'Research Infrastructure'),
    ('RocketLaunchTeam', 'Rocket Launch Team'),
    ('SpecialInitiatives', 'Special Initiatives'),
    ('StemBridgeScholarship', 'STEM Bridge Scholarship'),
    (
        'UndergraduateAerospaceDesignResearchScholarship',
        'Undergraduate Aerospace Design Research Scholarship'
    ),
    ('UndergraduateResearch', 'Undergraduate Research Fellowship'),
    ('UndergraduateScholarship', 'Undergraduate Scholarship'),
    (
        'UnmannedAerialVehiclesResearchScholarship',
        'Unmanned Aerial Vehicles Research Scholarship',
    ),
    ('WomenInAviationScholarship', 'Women in Aviation Scholarship'),
)
