YEAR_CHOICES = (
    ('','---------'),
    ('1','Freshman'),
    ('2','Sophmore'),
    ('3','Junior'),
    ('4','Senior'),
)
GRADUATE_DEGREE = (
    ('M.S.','M.S.'),
    ('Ph.D','Ph.D'),
    ('M.D.','M.D.'),
    ('Other','Other')
)

UNDERGRADUATE_DEGREE = (
    ("Bachelor's degree","Bachelor's degree"),
    ("Associate's degree/certificate","Associate's degree/certificate")
)

WSGC_SCHOOL = (
    ('Alverno College','Alverno College'),
    ('Carroll University','Carroll University'),
    ('Carthage College','Carthage College'),
    ('Chief Dull Knife College','Chief Dull Knife College'),
    ('College of Menominee Nation','College of Menominee Nation'),
    ('Colorado School of Mines','Colorado School of Mines'),
    ('Concordia University','Concordia University'),
    ('Fond du Lac Tribal Community College','Fond du Lac Tribal Community College'),
    ('Lawrence University','Lawrence University'),
    ('Leech Lake Technical College','Leech Lake Technical College'),
    ('Little Big Horn College','Little Big Horn College'),
    ('Marquette University','Marquette University'),
    ('Medical College of Wisconsin','Medical College of Wisconsin'),
    ('Milwaukee School of Engineering','Milwaukee School of Engineering'),
    ('Northern Arizona University','Northern Arizona University'),
    ('Northwest Indian College','Northwest Indian College'),
    ('Ripon College','Ripon College'),
    ('St. Norbert College','St. Norbert College'),
    ('Turtle Mountain Community College','Turtle Mountain Community College'),
    ('University of Alaska-Fairbanks','University of Alaska-Fairbanks'),
    ('University of California-Los Angeles','University of California-Los Angeles'),
    ('UW Fox Valley','UW Fox Valley'),
    ('UW Green Bay','UW Green Bay'),
    ('UW LaCrosse','UW LaCrosse'),
    ('UW Madison','UW Madison'),
    ('UW Milwaukee','UW Milwaukee'),
    ('UW Oshkosh','UW Oshkosh'),
    ('UW Parkside','UW Parkside'),
    ('UW Platteville','UW Platteville'),
    ('UW River Falls','UW River Falls'),
    ('UW Sheboygan','UW Sheboygan'),
    ('UW Stevens Point','UW Stevens Point'),
    ('UW Stout','UW Stout'),
    ('UW Superior','UW Superior'),
    ('UW Washington County','UW Washington County'),
    ('UW Whitewater','UW Whitewater'),
    ('Utah State University-Eastern Blanding','Utah State University-Eastern Blanding'),
    ('Western Technical College','Western Technical College'),
    ('Wisconsin Lutheran College','Wisconsin Lutheran College')
)

MAJORS = (
    ('Aeronautical Engineering','Aeronautical Engineering'),
    ('Aerospace Engineering','Aerospace Engineering'),
    ('Applied Physics','Applied Physics'),
    ('Astronomy','Astronomy'),
    ('Astrophysics','Astrophysics'),
    ('Atmoshperic Sciences','Atmoshperic Sciences'),
    ('Biochemistry','Biochemistry'),
    ('Biology','Biology'),
    ('Biomedical Engineering','Biomedical Engineering'),
    ('Biomedical Science','Biomedical Science'),
    ('Biophysics','Biophysics'),
    ('Biotechnology','Biotechnology'),
    ('Chemical Engineering','Chemical Engineering'),
    ('Chemistry','Chemistry'),
    ('Civil Engineering','Civil Engineering'),
    ('Computer Engineering','Computer Engineering'),
    ('Computer Science','Computer Science'),
    ('Electrical Engineering','Electrical Engineering'),
    ('Environmental Science','Environmental Science'),
    ('Environmental Studies','Environmental Studies'),
    ('Geography','Geography'),
    ('Geology','Geology'),
    ('Geophysics','Geophysics'),
    ('Geoscience','Geoscience'),
    ('Industrial Engineering','Industrial Engineering'),
    ('Kinesiology','Kinesiology'),
    ('Mathematics','Mathematics'),
    ('Mechanical Engineering','Mechanical Engineering'),
    ('Meteorology','Meteorology'),
    ('Microbiology','Microbiology'),
    ('Molecular and Cell Biology','Molecular and Cell Biology'),
    ('Molecular and Environmental Plant Science','Molecular and Environmental Plant Science'),
    ('Neuroscience','Neuroscience'),
    ('Nuclear Engineering','Nuclear Engineering'),
    ('Oceanography','Oceanography'),
    ('Other','Other'),
    ('Physics','Physics'),
    ('Statistics','Statistics'),
    ('Systems Engineering','Systems Engineering')
)
